[package]
name = "Rust-Tuto"
version = "0.1.0"
authors = ["Alexis Lina <alexis.lina@sewan.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
